[build-system]
requires = [
]

[project]
name = "Gitor"
version = "0.0.1"
authors = [
  { name="Monnapse", email="masonshuber@gmail.com" },
]
description = "Github python wrapper, Custom made for getting repositories for your python web server."
readme = "README.md"